#!/bin/bash

# Capture app name
app="$2"

# Configuration files
runWithDgpuFile="/tmp/regataos-prime/config/run-with-dgpu.conf"
runWithoutDgpuFile="/tmp/regataos-prime/config/run-without-dgpu.conf"
regataosPrimeConfigFile="/tmp/regataos-prime/config/regataos-prime.conf"

# Enable or disable application execution with the dGPU
function dgpu_app() {
	# Enable application execution with the dGPU
	checkRunWithoutDgpu="$(grep -r "$app" "$runWithoutDgpuFile")"
	checkRegataosPrimeConfigFile="$(grep -r "all-apps" "$regataosPrimeConfigFile")"

	if [[ "$checkRunWithoutDgpu" == *"$app"* ]]; then
		if [[ "$checkRegataosPrimeConfigFile" == *"all-apps=off"* ]]; then
			if [[ "$checkRunWithoutDgpu" == *"$app=on"* ]]; then
				sed -i "s/$app=on//" "$runWithoutDgpuFile"
				sed -i "s/$app//" "$runWithoutDgpuFile"
			else
				sed -i "s/$app/$app=on/" "$runWithoutDgpuFile"
			fi
		else
			sed -i "s/$app=on//" "$runWithoutDgpuFile"
			sed -i "s/$app//" "$runWithoutDgpuFile"
		fi

		# Indicate that not all apps are running with the dGPU
		if test ! -s "$runWithoutDgpuFile" ; then
			sed -i 's/\(one-apps=off\)/one-apps=on/' "$regataosPrimeConfigFile"
		fi

	else
		# Disable application execution with the dGPU
		echo "$app" >> "$runWithoutDgpuFile"

		# Indicate that not all apps are running with the dGPU
		if [[ $(grep -r one-apps "$regataosPrimeConfigFile") == *"one-apps=on"* ]]; then
			sed -i 's/\(one-apps=on\)/one-apps=off/' "$regataosPrimeConfigFile"
		fi
	fi

	# Fix external app
	sed -i "s/external-app1=on0/external-app10/" "$runWithoutDgpuFile"

	# Clear empty lines
	sed -i '/^$/d' "$runWithoutDgpuFile"
	sed -i '/^0/d' "$runWithoutDgpuFile"
	sed -i '/^=on/d' "$runWithoutDgpuFile"

	# Indicate that not all apps are running with the dGPU
	if test ! -s "$runWithoutDgpuFile" ; then
		sed -i 's/\(one-apps=off\)/one-apps=on/' "$regataosPrimeConfigFile"
	fi
}

# Disable running with dGPU for all applications
function disable_run_dgpu() {
	sed -i 's/\(all-apps=on\)/all-apps=off/' "$regataosPrimeConfigFile"
	sed -i 's/\(one-apps=on\)/one-apps=off/' "$regataosPrimeConfigFile"
	echo "" > "$runWithDgpuFile"
}

# Enable running with dGPU for all applications
function enable_run_dgpu() {
	sed -i 's/\(all-apps=off\)/all-apps=on/' "$regataosPrimeConfigFile"
	sed -i 's/\(one-apps=off\)/one-apps=on/' "$regataosPrimeConfigFile"
	echo "" > "$runWithoutDgpuFile"
}

case $1 in
   "-dgpu-app") dgpu_app
        ;;
   "-disable-run-dgpu") disable_run_dgpu
        ;;
   "-enable-run-dgpu") enable_run_dgpu
        ;;
   *) echo "Invalid option!"
    	exit 1
    	;;
esac
