#!/bin/bash

cd /

while :
do

# Wait until the environment loads.
ps -C "plasmashell" > /dev/null
if [ $? = 0 ]; then
	sudo /opt/regataos-prime/scripts/apps-hybrid-graphics
	break
fi

   sleep 1
done
