#!/bin/bash

# Enable or disable application execution with the dGPU
#Capture app name
app="$2"

function dgpu_app() {
	# Enable application execution with the dGPU
	if [[ $(grep -r "$app" "/tmp/regataos-prime/config/run-without-dgpu.conf") == *"$app"* ]]; then
		if [[ $(grep -r all-apps "/tmp/regataos-prime/config/regataos-prime.conf") == *"all-apps=off"* ]]; then
			if [[ $(grep -r "$app=on" "/tmp/regataos-prime/config/run-without-dgpu.conf") == *"$app=on"* ]]; then
				sed -i "s/$app=on//" "/tmp/regataos-prime/config/run-without-dgpu.conf"
				sed -i "s/$app//" "/tmp/regataos-prime/config/run-without-dgpu.conf"

			else
				sed -i "s/$app/$app=on/" "/tmp/regataos-prime/config/run-without-dgpu.conf"
			fi
		else
			sed -i "s/$app//" "/tmp/regataos-prime/config/run-without-dgpu.conf"
		fi

		# Indicate that not all apps are running with the dGPU
		if test ! -s "/tmp/regataos-prime/config/run-without-dgpu.conf" ; then
			sed -i 's/\(one-apps=off\)/one-apps=on/' "/tmp/regataos-prime/config/regataos-prime.conf"
		fi

	else
		# Disable application execution with the dGPU
		echo "$app" >> "/tmp/regataos-prime/config/run-without-dgpu.conf"

		# Indicate that not all apps are running with the dGPU
		if [[ $(grep -r one-apps "/tmp/regataos-prime/config/regataos-prime.conf") == *"one-apps=on"* ]]; then
			sed -i 's/\(one-apps=on\)/one-apps=off/' "/tmp/regataos-prime/config/regataos-prime.conf"
		fi
	fi

	# Fix external app
	sed -i "s/external-app1=on0/external-app10/" "/tmp/regataos-prime/config/run-without-dgpu.conf"

	# Clear empty lines
	sed -i '/^$/d' "/tmp/regataos-prime/config/run-without-dgpu.conf"
	sed -i '/^0/d' "/tmp/regataos-prime/config/run-without-dgpu.conf"

	# Indicate that not all apps are running with the dGPU
	if test ! -s "/tmp/regataos-prime/config/run-without-dgpu.conf" ; then
		sed -i 's/\(one-apps=off\)/one-apps=on/' "/tmp/regataos-prime/config/regataos-prime.conf"
	fi
}

# Disable running with dGPU for all applications
function disable_run_dgpu() {
	sed -i 's/\(all-apps=on\)/all-apps=off/' "/tmp/regataos-prime/config/regataos-prime.conf"
	sed -i 's/\(one-apps=on\)/one-apps=off/' "/tmp/regataos-prime/config/regataos-prime.conf"
}

# Enable running with dGPU for all applications
function enable_run_dgpu() {
	sed -i 's/\(all-apps=off\)/all-apps=on/' "/tmp/regataos-prime/config/regataos-prime.conf"
	sed -i 's/\(one-apps=off\)/one-apps=on/' "/tmp/regataos-prime/config/regataos-prime.conf"
	echo "" > "/tmp/regataos-prime/config/run-without-dgpu.conf"
}

case $1 in
   "-dgpu-app") dgpu_app
         ;;
   "-disable-run-dgpu") disable_run_dgpu
         ;;
   "-enable-run-dgpu") enable_run_dgpu
         ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
