#!/bin/bash

# App info
app_name="$1"
package_name="$2"
package_manager="$3"
app_executable="$4"

# Find the user's desktop
user=$(users | awk '{print $1}')
test -f "${XDG_CONFIG_HOME:-/home/$user/.config}/user-dirs.dirs" && source "${XDG_CONFIG_HOME:-/home/$user/.config}/user-dirs.dirs"
desktop_dir="${XDG_DESKTOP_DIR:-/home/$user/Desktop}"
desktop_folder="$(echo $desktop_dir | cut -d/ -f 3-)"

# Directories where possible .desktop files for apps
apps_dir="/usr/share/applications"
desktop_dir="/home/$user/$desktop_folder"
apps_local_home_dir="/home/$user/.local/share/applications"
apps_local_dir="/usr/local/share/applications"
snap_dir="/var/lib/snapd/desktop/applications"
flatpak_dir="/var/lib/flatpak/exports/share/applications"

# Detect file manager
if [[ $(echo $package_manager) == *"zypper"* ]]; then
	desktop_file_dir=$(rpm -ql $package_name | grep ".desktop" | head -1 | tail -1 | sed 's/\// /g' | sed 's/local //' | awk '{print $4}')

	if [ -z $desktop_file_dir ]; then
		check_fake_desktop_file=$(rpm -ql $package_name | grep ".desktop")
		desktop_file=$(cat $check_fake_desktop_file | head -5 | tail -1 | cut -d"=" -f 2- | sed 's/\// /g' | sed 's/local //' | awk '{print $4}')
		echo "$desktop_file"
	else
		desktop_file=$(echo $desktop_file_dir)
		echo "$desktop_file"
	fi

	# Enable or disable running applications with the dGPU
	if [[ $(grep -R "$app_name=on" /tmp/regataos-prime/config/run-without-dgpu.conf) == *"$app_name=on"* ]]; then
		# Run app with the dGPU
		if [[ $(grep -r "regataos-dgpu" "$apps_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$apps_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$apps_dir/$desktop_file"
		fi

		if [[ $(grep -r "regataos-dgpu" "$desktop_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$desktop_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$desktop_dir/$desktop_file"
		fi

		if [[ $(grep -r "regataos-dgpu" "$apps_local_home_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$apps_local_home_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$apps_local_home_dir/$desktop_file"
		fi

		if [[ $(grep -r "regataos-dgpu" "$apps_local_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$apps_local_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$apps_local_dir/$desktop_file"
		fi

		# Add the app name to the list of apps running with the dGPU and clear empty lines
		if [[ $(grep -R "$app_name" /tmp/regataos-prime/config/run-with-dgpu.conf) != *"$app_name"* ]]; then
			echo "$app_name" >>"/tmp/regataos-prime/config/run-with-dgpu.conf"
			sed -i '/^$/d' "/tmp/regataos-prime/config/run-with-dgpu.conf"
		fi

		# Remove the app name to the list of apps not running with the dGPU and clear empty lines
		sed -i "s/$app_name//" "/tmp/regataos-prime/config/run-without-dgpu.conf"
		sed -i '/^$/d' "/tmp/regataos-prime/config/run-without-dgpu.conf"

	elif [[ $(grep -R 'all-apps' /tmp/regataos-prime/config/regataos-prime.conf | cut -d'=' -f 2-) == *"off"* ]]; then
		# Run app without the dGPU
		sed -i 's/Exec=regataos-dgpu /Exec=/' "$apps_dir/$desktop_file" "$desktop_dir/$desktop_file" "$apps_local_home_dir/$desktop_file" "$apps_local_dir/$desktop_file"

		# Add the app name to the list of apps not running with the dGPU and clear empty lines
		if [[ $(grep -R "$app_name" /tmp/regataos-prime/config/run-without-dgpu.conf) != *"$app_name"* ]]; then
			echo "$app_name" >>"/tmp/regataos-prime/config/run-without-dgpu.conf"
			sed -i '/^$/d' "/tmp/regataos-prime/config/run-without-dgpu.conf"
		fi

		# Remove the app name to the list of apps running with the dGPU and clear empty lines
		sed -i "s/$app_name//" "/tmp/regataos-prime/config/run-with-dgpu.conf"
		sed -i '/^$/d' "/tmp/regataos-prime/config/run-with-dgpu.conf"

	elif [[ $(grep -R "$app_name" /tmp/regataos-prime/config/run-without-dgpu.conf) == *"$app_name"* ]]; then
		# Run app without the dGPU
		sed -i 's/Exec=regataos-dgpu /Exec=/' "$apps_dir/$desktop_file" "$desktop_dir/$desktop_file" "$apps_local_home_dir/$desktop_file" "$apps_local_dir/$desktop_file"

		# Add the app name to the list of apps not running with the dGPU and clear empty lines
		if [[ $(grep -R "$app_name" /tmp/regataos-prime/config/run-without-dgpu.conf) != *"$app_name"* ]]; then
			echo "$app_name" >>"/tmp/regataos-prime/config/run-without-dgpu.conf"
			sed -i '/^$/d' "/tmp/regataos-prime/config/run-without-dgpu.conf"
		fi

		# Remove the app name to the list of apps running with the dGPU and clear empty lines
		sed -i "s/$app_name//" "/tmp/regataos-prime/config/run-with-dgpu.conf"
		sed -i '/^$/d' "/tmp/regataos-prime/config/run-with-dgpu.conf"

	else
		# Run app with the dGPU
		if [[ $(grep -r "regataos-dgpu" "$apps_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$apps_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$apps_dir/$desktop_file"
		fi

		if [[ $(grep -r "regataos-dgpu" "$desktop_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$desktop_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$desktop_dir/$desktop_file"
		fi

		if [[ $(grep -r "regataos-dgpu" "$apps_local_home_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$apps_local_home_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$apps_local_home_dir/$desktop_file"
		fi

		if [[ $(grep -r "regataos-dgpu" "$apps_local_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$apps_local_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$apps_local_dir/$desktop_file"
		fi

		# Add the app name to the list of apps running with the dGPU and clear empty lines
		if [[ $(grep -R "$app_name" /tmp/regataos-prime/config/run-with-dgpu.conf) != *"$app_name"* ]]; then
			echo "$app_name" >>"/tmp/regataos-prime/config/run-with-dgpu.conf"
			sed -i '/^$/d' "/tmp/regataos-prime/config/run-with-dgpu.conf"
		fi

		# Remove the app name to the list of apps not running with the dGPU and clear empty lines
		sed -i "s/$app_name//" "/tmp/regataos-prime/config/run-without-dgpu.conf"
		sed -i '/^$/d' "/tmp/regataos-prime/config/run-without-dgpu.conf"
	fi

elif [[ $(echo $package_manager) == *"snap"* ]]; then
	# Locate the Snap app .desktop file
	search_desktop_snap_file=$(grep -r $(echo "$app_executable" | sed 's/snap run //') "/var/lib/snapd/desktop/applications/" | sed '/mimeinfo/d' | grep .desktop | head -1 | tail -1 | cut -d":" -f -1 | sed '/^$/d')

	# Get the name of the .desktop file from the Snap app
	desktop_file=$(echo "$search_desktop_snap_file" | sed 's/\// /g' | awk '{print $6}')

	echo "$app_executable" >/tmp/regataos-prime/teste.txt

	# Enable or disable running applications with the dGPU
	if [[ $(grep -R "$app_name=on" /tmp/regataos-prime/config/run-without-dgpu.conf) == *"$app_name=on"* ]]; then
		# Run app with the dGPU
		if [[ $(grep -r "regataos-dgpu" "$snap_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$snap_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$snap_dir/$desktop_file"
		fi

		if [[ $(grep -r "regataos-dgpu" "$desktop_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$desktop_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$desktop_dir/$desktop_file"
		fi

		if [[ $(grep -r "regataos-dgpu" "$apps_local_home_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$apps_local_home_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$apps_local_home_dir/$desktop_file"
		fi

		# Add the app name to the list of apps running with the dGPU and clear empty lines
		if [[ $(grep -R "$app_name" /tmp/regataos-prime/config/run-with-dgpu.conf) != *"$app_name"* ]]; then
			echo "$app_name" >>"/tmp/regataos-prime/config/run-with-dgpu.conf"
			sed -i '/^$/d' "/tmp/regataos-prime/config/run-with-dgpu.conf"
		fi

		# Remove the app name to the list of apps not running with the dGPU and clear empty lines
		sed -i "s/$app_name//" "/tmp/regataos-prime/config/run-without-dgpu.conf"
		sed -i '/^$/d' "/tmp/regataos-prime/config/run-without-dgpu.conf"

	elif [[ $(grep -R 'all-apps' /tmp/regataos-prime/config/regataos-prime.conf | cut -d'=' -f 2-) == *"off"* ]]; then
		# Run app without the dGPU
		sed -i 's/Exec=regataos-dgpu /Exec=/' "$snap_dir/$desktop_file" "$desktop_dir/$desktop_file" "$apps_local_home_dir/$desktop_file"

		# Add the app name to the list of apps not running with the dGPU and clear empty lines
		if [[ $(grep -R "$app_name" /tmp/regataos-prime/config/run-without-dgpu.conf) != *"$app_name"* ]]; then
			echo "$app_name" >>"/tmp/regataos-prime/config/run-without-dgpu.conf"
			sed -i '/^$/d' "/tmp/regataos-prime/config/run-without-dgpu.conf"
		fi

		# Remove the app name to the list of apps running with the dGPU and clear empty lines
		sed -i "s/$app_name//" "/tmp/regataos-prime/config/run-with-dgpu.conf"
		sed -i '/^$/d' "/tmp/regataos-prime/config/run-with-dgpu.conf"

	elif [[ $(grep -R "$app_name" /tmp/regataos-prime/config/run-without-dgpu.conf) == *"$app_name"* ]]; then
		# Run app without the dGPU
		sed -i 's/Exec=regataos-dgpu /Exec=/' "$snap_dir/$desktop_file" "$desktop_dir/$desktop_file" "$apps_local_home_dir/$desktop_file"

		# Add the app name to the list of apps not running with the dGPU and clear empty lines
		if [[ $(grep -R "$app_name" /tmp/regataos-prime/config/run-without-dgpu.conf) != *"$app_name"* ]]; then
			echo "$app_name" >>"/tmp/regataos-prime/config/run-without-dgpu.conf"
			sed -i '/^$/d' "/tmp/regataos-prime/config/run-without-dgpu.conf"
		fi

		# Remove the app name to the list of apps running with the dGPU and clear empty lines
		sed -i "s/$app_name//" "/tmp/regataos-prime/config/run-with-dgpu.conf"
		sed -i '/^$/d' "/tmp/regataos-prime/config/run-with-dgpu.conf"

	else
		# Run app with the dGPU
		if [[ $(grep -r "regataos-dgpu" "$snap_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$snap_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$snap_dir/$desktop_file"
		fi

		if [[ $(grep -r "regataos-dgpu" "$desktop_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$desktop_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$desktop_dir/$desktop_file"
		fi

		if [[ $(grep -r "regataos-dgpu" "$apps_local_home_dir/$desktop_file") != *"regataos-dgpu"* ]]; then
			sed -i 's/Exec=/Exec=regataos-dgpu /' "$apps_local_home_dir/$desktop_file"
			sed -i 's/TryExec=regataos-dgpu /TryExec=/' "$apps_local_home_dir/$desktop_file"
		fi

		# Add the app name to the list of apps running with the dGPU and clear empty lines
		if [[ $(grep -R "$app_name" /tmp/regataos-prime/config/run-with-dgpu.conf) != *"$app_name"* ]]; then
			echo "$app_name" >>"/tmp/regataos-prime/config/run-with-dgpu.conf"
			sed -i '/^$/d' "/tmp/regataos-prime/config/run-with-dgpu.conf"
		fi

		# Remove the app name to the list of apps not running with the dGPU and clear empty lines
		sed -i "s/$app_name//" "/tmp/regataos-prime/config/run-without-dgpu.conf"
		sed -i '/^$/d' "/tmp/regataos-prime/config/run-without-dgpu.conf"
	fi

else
	echo "Nothing to do..."
fi

# Clear empty lines
sed -i '/^$/d' "$runWithoutDgpuFile"
sed -i '/^0/d' "$runWithoutDgpuFile"
sed -i '/^=on/d' "$runWithoutDgpuFile"
