#!/bin/bash

# Enable/Disable TearFree
function tearfree() {
	if [[ $(cat /tmp/regataos-prime/config/regataos-prime.conf) == *"tearfree=on"* ]]; then
		sed -i 's/\(tearfree=on\)/tearfree=off/' "/tmp/regataos-prime/config/regataos-prime.conf"
		sudo /opt/regataos-prime/scripts/gpu-render -tearfree-off

		#For NVIDIA Driver
		sleep 3
		nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = Off }"

		#For open source drivers
		screen=$(xrandr --props | grep 'connected primary' | awk '{print $1}')
		xrandr --output $screen --set TearFree off

		# Show notify on desktop
		/bin/bash /opt/regataos-prime/scripts/notify -tearfree-off

	elif [[ $(cat /tmp/regataos-prime/config/regataos-prime.conf) == *"tearfree=off"* ]]; then
		sed -i 's/\(tearfree=off\)/tearfree=on/' "/tmp/regataos-prime/config/regataos-prime.conf"
		sudo /opt/regataos-prime/scripts/gpu-render -tearfree-on

		#For NVIDIA Driver
		sleep 3
		nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"

		#For open source drivers
		screen=$(xrandr --props | grep 'connected primary' | awk '{print $1}')
		xrandr --output $screen --set TearFree on

		# Show notify on desktop
		/bin/bash /opt/regataos-prime/scripts/notify -tearfree-on

	else
		echo "Option not found in the file with configuration options."
	fi
}

# Enable/Disable FreeSync
function enable_freesync() {
	screen=$(xrandr --props | grep 'connected primary' | awk '{print $1}')
	echo "Enabling FreeSync on $screen"
	DISPLAY=:0 xrandr --output $screen --set "freesync" 1
	xrandr --output $screen --set "freesync" 1
	sed -i 's/\(freesync=off\)/freesync=on/' "/tmp/regataos-prime/config/regataos-prime.conf"

	# Show notify on desktop
	/bin/bash /opt/regataos-prime/scripts/notify -tearfree-on
}

function disable_freesync() {
	screen=$(xrandr --props | grep 'connected primary' | awk '{print $1}')
	echo "Disabling FreeSync on $screen"
	DISPLAY=:0 xrandr --output $screen --set "freesync" 0
	xrandr --output $screen --set "freesync" 0
	sed -i 's/\(freesync=on\)/freesync=off/' "/tmp/regataos-prime/config/regataos-prime.conf"

	# Show notify on desktop
	/bin/bash /opt/regataos-prime/scripts/notify -tearfree-off
}

# Configuration option for KWin compositing
function compositor() {
	# Check if the "compositor" option is present in the configuration file
	if [[ $(grep -r "compositor=" "/tmp/regataos-prime/config/regataos-prime.conf") != *"compositor="* ]]; then
		echo "compositor=on" >> "$HOME/.config/regataos-prime/regataos-prime.conf"
		sed -i '/^$/d' "$HOME/.config/regataos-prime/regataos-prime.conf"
	fi

	# Disable or enable KWin compositing
	if [[ $(cat /tmp/regataos-prime/config/regataos-prime.conf) == *"compositor=on"* ]]; then
		sed -i 's/\(compositor=on\)/compositor=off/' "/tmp/regataos-prime/config/regataos-prime.conf"
		qdbus org.kde.KWin /Compositor suspend

		# Show notify on desktop
		sleep 2
		/bin/bash /opt/regataos-prime/scripts/notify -compositor-off

	elif [[ $(cat /tmp/regataos-prime/config/regataos-prime.conf) == *"compositor=off"* ]]; then
		sed -i 's/\(compositor=off\)/compositor=on/' "/tmp/regataos-prime/config/regataos-prime.conf"
		qdbus org.kde.KWin /Compositor resume

		# Show notify on desktop
		sleep 2
		/bin/bash /opt/regataos-prime/scripts/notify -compositor-on

	else
		sed -i 's/\(compositor=on\)/compositor=off/' "/tmp/regataos-prime/config/regataos-prime.conf"
		qdbus org.kde.KWin /Compositor suspend

		# Show notify on desktop
		sleep 2
		/bin/bash /opt/regataos-prime/scripts/notify -compositor-off
	fi
}

case $1 in
   "-tearfree") tearfree
         ;;
   "-freesync-on") enable_freesync
         ;;
   "-freesync-off") disable_freesync
         ;;
   "-compositor") compositor
         ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
