#!/bin/bash

# PRIME Settings notification system

# Configure the dGPU manufacturer's logo
if test -e /usr/bin/nvidia-xconfig ; then
	logo_gpu="nvidia-dgpu"
else
	logo_gpu="amd-dgpu"
fi

# Notify the user that a restart is required
function restart_system() {
	notify-send -i chronometer-reset -u normal -a 'PRIME Settings' "Reiniciar o Regata OS" \
	"É necessário reiniciar para que as mudanças tenham efeito no Regata OS."
}

# Notify when dGPU is disabled or enabled for all applications
function disable_run_dgpu() {
	if test -e /usr/bin/nvidia-xconfig ; then
		logo_gpu="nvidia-dgpu-off"
	else
		logo_gpu="amd-dgpu-off"
	fi

	notify-send -i $logo_gpu -u normal -a 'PRIME Settings' "Não renderizar com a dGPU" \
	"Não renderizar os aplicativos listados no PRIME Settings com a dGPU."
}

function enable_run_dgpu() {
	notify-send -i $logo_gpu -u normal -a 'PRIME Settings' "Renderizar com a dGPU" \
	"Renderizar os aplicativos listados no PRIME Settings com a dGPU."
}

# Running app or game with dGPU
function running_with_dgpu() {
	if test -e /usr/bin/nvidia-xconfig ; then
		notify-send -i $logo_gpu -u normal -a 'PRIME Settings' "Renderizando com a dGPU" \
		"Usando a GPU NVIDIA para a renderização gráfica."
	else
		notify-send -i $logo_gpu -u normal -a 'PRIME Settings' "Renderizando com a dGPU" \
		"Usando a GPU AMD para a renderização gráfica."
	fi
}

# Notify copy of information to the clipboard
function copy_info() {
	notify-send -i emblem-ok-symbolic -u normal -a 'PRIME Settings' "Informações copiadas" \
	"Informações copiadas para área de transferência."
}

# CPU governor
function cpu_powersave() {
	notify-send -i preferences-system-power-management -u normal -a 'PRIME Settings' "Equilibrado" \
	"Fazer o equilíbrio entre o desempenho e o consumo de energia."
}

function cpu_performance() {
	notify-send -i preferences-system-power-management -u normal -a 'PRIME Settings' "Alto desempenho" \
	"Dar prioridade ao desempenho; pode consumir mais energia."
}

case $1 in
   "-restart") restart_system
        ;;
   "-disable-run-dgpu") disable_run_dgpu
        ;;
   "-enable-run-dgpu") enable_run_dgpu
        ;;
   "-running-with-dgpu") running_with_dgpu
        ;;
   "-copy-info") copy_info
        ;;
   "-cpu-powersave") cpu_powersave
        ;;
   "-cpu-performance") cpu_performance
        ;;
   *) echo "Invalid option!"
    	exit 1
    	;;
esac
